arm1:
    #list of controllers
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    joint1_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint1
      pid: {p: 1, i: 0.001, d: 0.002}
    joint2_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint2
      pid: {p: 1, i: 0.001, d: 0.002}
    joint3_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint3
      pid: {p: 1, i: 0.001, d: 0.002}
    joint4_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint4
      pid: {p: 1, i: 0.001, d: 0.002}
    right_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: right_joint
      pid: {p: 1, i: 0.001, d: 0.002}
    left_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: left_joint
      pid: {p: 1, i: 0.001, d: 0.002}

